version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: mdd-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/backend/models
      - ./backend/dataset:/app/backend/dataset

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: mdd-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
